
version: '3.8'
services:
  ingest:
    build: ./ingest
    volumes:
      - ./data:/data
      - shared_data:/shared

  process:
    build: ./process
    depends_on:
      - ingest
    volumes:
      - shared_data:/shared

volumes:
  shared_data:
